/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_design;

import chatbot.Client.Client;

import javax.swing.*;
import java.util.Map;

/**
 * @author tldlir001
 */
public class GUI extends javax.swing.JFrame
{
	private static Map<Integer, String> knownClients;
	private static Client client;

	/**
	 * Creates new form GUI
	 */
	public GUI()
	{
		initComponents();
		updateClients();
	}

	public void updateClients()
	{
		// Does this need to be in another thread (only here because need to wait for a response)?
		Thread waitForClients = new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				client.recievedClients = false;
				client.sendToServer("reqclients::", " ");

				// need to wait till client has the response from server
				while (!client.recievedClients)
					btn_refresh.setEnabled(false);

				btn_refresh.setEnabled(true);

				knownClients = client.knownClients;
				System.out.println(knownClients.size());
				DefaultListModel<String> dlm = new DefaultListModel<>();
				for (String client : knownClients.values())
				{
					dlm.addElement(client);
				}
				list_members.setModel(dlm);
			}
		});

		waitForClients.run();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		list_members = new javax.swing.JList<>();
		btn_group = new javax.swing.JButton();
		lbl_grpmem = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		list_groups = new javax.swing.JList<>();
		lbl_actgrp = new javax.swing.JLabel();
		btn_chat = new javax.swing.JButton();
		btn_GroupChat = new javax.swing.JButton();
		btn_refresh = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		list_members.setModel(new javax.swing.AbstractListModel<String>()
		{
			String[] strings = {"Liron", "sasha", "shane"};

			public int getSize() { return strings.length; }

			public String getElementAt(int i) { return strings[i]; }
		});
		jScrollPane2.setViewportView(list_members);

		btn_group.setText("Create Group");

		lbl_grpmem.setText("Online members");

		list_groups.setModel(new javax.swing.AbstractListModel<String>()
		{
			String[] strings = {"Global", "group1", "group2"};

			public int getSize() { return strings.length; }

			public String getElementAt(int i) { return strings[i]; }
		});
		jScrollPane3.setViewportView(list_groups);

		lbl_actgrp.setText("Active Groups:");

		btn_chat.setText("Chat");
		btn_chat.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btn_chatActionPerformed(evt);
			}
		});

		btn_GroupChat.setText("Group chat");

		btn_refresh.setText("Refresh");
		btn_refresh.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btn_refreshActionPerformed(evt);
			}
		});

		jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btn_group, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(lbl_grpmem, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(lbl_actgrp, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btn_chat, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btn_GroupChat, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btn_refresh, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
		jLayeredPane1.setLayout(jLayeredPane1Layout);
		jLayeredPane1Layout.setHorizontalGroup(
				jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jLayeredPane1Layout.createSequentialGroup()
								.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment
										.LEADING)
										.addGroup(jLayeredPane1Layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing
														.GroupLayout.Alignment.LEADING, false)
														.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing
																.GroupLayout.Alignment.TRAILING)
																.addComponent(jScrollPane2, javax.swing.GroupLayout
																		.PREFERRED_SIZE, 142, javax.swing.GroupLayout
																		.PREFERRED_SIZE)
																.addComponent(lbl_grpmem, javax.swing.GroupLayout
																		.Alignment.LEADING))
														.addGroup(jLayeredPane1Layout.createSequentialGroup()
																.addComponent(btn_chat)
																.addPreferredGap(javax.swing.LayoutStyle
																		.ComponentPlacement.RELATED, javax.swing
																		.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(btn_GroupChat)))
												.addGap(18, 18, 18)
												.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing
														.GroupLayout.Alignment.LEADING, false)
														.addComponent(jScrollPane3)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jLayeredPane1Layout.createSequentialGroup()
																		.addComponent(lbl_actgrp)
																		.addGap(18, 18, 18))
														.addComponent(btn_group, javax.swing.GroupLayout
																.PREFERRED_SIZE, 130, javax.swing.GroupLayout
																.PREFERRED_SIZE)))
										.addGroup(jLayeredPane1Layout.createSequentialGroup()
												.addGap(118, 118, 118)
												.addComponent(btn_refresh)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jLayeredPane1Layout.setVerticalGroup(
				jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jLayeredPane1Layout.createSequentialGroup()
								.addComponent(btn_refresh)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment
										.BASELINE)
										.addComponent(lbl_grpmem)
										.addComponent(lbl_actgrp))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment
										.LEADING, false)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short
												.MAX_VALUE)
										.addComponent(jScrollPane3))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment
										.LEADING)
										.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout
												.Alignment.BASELINE)
												.addComponent(btn_group)
												.addComponent(btn_GroupChat))
										.addComponent(btn_chat))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout
								.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLayeredPane1)
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btn_chatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_chatActionPerformed
	{//GEN-HEADEREND:event_btn_chatActionPerformed
		new ChatRoom().setVisible(true);
	}//GEN-LAST:event_btn_chatActionPerformed

	private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_refreshActionPerformed
	{//GEN-HEADEREND:event_btn_refreshActionPerformed
		updateClients();
	}//GEN-LAST:event_btn_refreshActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
	    /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>


		String name = JOptionPane.showInputDialog("Enter name");
		if (name == null) return; // if pressed cancel or close

		client = new Client(name);
		client.startListening();

		knownClients = client.knownClients;


        /* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_GroupChat;
	private javax.swing.JButton btn_chat;
	private javax.swing.JButton btn_group;
	private javax.swing.JButton btn_refresh;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JLabel lbl_actgrp;
	private javax.swing.JLabel lbl_grpmem;
	private javax.swing.JList<String> list_groups;
	private javax.swing.JList<String> list_members;
	// End of variables declaration//GEN-END:variables
}
